# Generated by Django 4.1.4 on 2022-12-12 10:36

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название товара')),
                ('article', models.IntegerField(verbose_name='Артикул')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('В наличии', 'В наличии'), ('Под заказ', 'Под заказ'), ('Ожидается поступление', 'Ожидается поступление'), ('Нет в наличии', 'Нет в наличии'), ('Не производится', 'Не производится')], max_length=21)),
                ('image', models.ImageField(upload_to=main.models.get_item_path, verbose_name='Изображение')),
            ],
        ),
    ]
